#
# Module manifest for module 'DefenderForCloudScripts'
#
# Generated by: Microsoft Defender for Cloud Team
#
# Generated on: 2024-01-30
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule           = 'DefenderForCloudScripts.psm1'

    # Version number of this module.
    ModuleVersion        = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = 'f8a7b9c2-3d4e-5f6a-7b8c-9d0e1f2a3b4c'

    # Author of this module
    Author               = 'Microsoft Defender for Cloud Team'

    # Company or vendor of this module
    CompanyName          = 'Microsoft Corporation'

    # Copyright statement for this module
    Copyright            = '(c) Microsoft Corporation. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Comprehensive PowerShell scripts for deploying, managing, troubleshooting, and monitoring Microsoft Defender for Cloud across enterprise environments. Includes deployment automation, government SOC capabilities, DevSecOps integration, diagnostic tools, incident response playbooks, and advanced threat hunting capabilities.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @(
        @{ModuleName = 'Az.Accounts'; ModuleVersion = '2.0.0' },
        @{ModuleName = 'Az.Resources'; ModuleVersion = '6.0.0' },
        @{ModuleName = 'Az.Security'; ModuleVersion = '1.0.0' },
        @{ModuleName = 'Az.Monitor'; ModuleVersion = '4.0.0' },
        @{ModuleName = 'Az.OperationalInsights'; ModuleVersion = '3.0.0' },
        @{ModuleName = 'Az.Automation'; ModuleVersion = '1.0.0' },
        @{ModuleName = 'Az.LogicApp'; ModuleVersion = '1.0.0' },
        @{ModuleName = 'Az.KeyVault'; ModuleVersion = '4.0.0' },
        @{ModuleName = 'Az.Storage'; ModuleVersion = '5.0.0' },
        @{ModuleName = 'Az.Compute'; ModuleVersion = '5.0.0' },
        @{ModuleName = 'Az.Network'; ModuleVersion = '6.0.0' }
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules        = @(
        'Deployment\Deploy-EnterpriseScaleArchitecture.ps1',
        'Deployment\Deploy-GovernmentSOC.ps1',
        'Deployment\Deploy-DevSecOpsIntegration.ps1',
        'Troubleshooting\Test-DefenderDiagnostics.ps1',
        'Troubleshooting\Invoke-DefenderAPIWithRetry.ps1',
        'Monitoring\Deploy-IncidentResponsePlaybooks.ps1',
        'Monitoring\Deploy-ThreatHuntingCapabilities.ps1'
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList             = @(
        'DefenderForCloudScripts.psm1',
        'DefenderForCloudScripts.psd1',
        'README.md',
        'Deployment\Deploy-EnterpriseScaleArchitecture.ps1',
        'Deployment\Deploy-GovernmentSOC.ps1',
        'Deployment\Deploy-DevSecOpsIntegration.ps1',
        'Troubleshooting\Test-DefenderDiagnostics.ps1',
        'Troubleshooting\Invoke-DefenderAPIWithRetry.ps1',
        'Monitoring\Deploy-IncidentResponsePlaybooks.ps1',
        'Monitoring\Deploy-ThreatHuntingCapabilities.ps1'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                       = @(
                'Microsoft',
                'Defender',
                'DefenderForCloud',
                'Security',
                'Azure',
                'SOC',
                'ThreatHunting',
                'IncidentResponse',
                'DevSecOps',
                'Compliance',
                'Government',
                'Enterprise',
                'Automation',
                'Monitoring',
                'Diagnostics',
                'NIST',
                'FedRAMP',
                'CJIS'
            )

            # A URL to the license for this module.
            LicenseUri                 = 'https://opensource.org/licenses/MIT'

            # A URL to the main website for this project.
            ProjectUri                 = 'https://github.com/microsoft/defender-for-cloud-scripts'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes               = @'
# Release Notes for DefenderForCloudScripts v1.0.0

## New Features

### Deployment Scripts
- **Deploy-EnterpriseScaleArchitecture.ps1**: Enterprise-scale deployment with multi-region support and compliance frameworks (NIST, FedRAMP, StateRAMP)
- **Deploy-GovernmentSOC.ps1**: Government SOC deployment with 24x7x365 monitoring, CJIS compliance, and classification-based retention
- **Deploy-DevSecOpsIntegration.ps1**: DevSecOps pipeline integration with security scanning, gates, and automated remediation

### Troubleshooting Scripts
- **Test-DefenderDiagnostics.ps1**: Comprehensive diagnostics for agent deployment, connectivity, policy compliance, and API authentication
- **Invoke-DefenderAPIWithRetry.ps1**: Robust API client with retry logic, rate limiting, and error handling

### Monitoring Scripts
- **Deploy-IncidentResponsePlaybooks.ps1**: Automated incident response workflows with Logic Apps, containment actions, and compliance reporting
- **Deploy-ThreatHuntingCapabilities.ps1**: Advanced threat hunting with KQL queries, MITRE ATT&CK mapping, and threat intelligence integration

## Key Capabilities

- **Multi-Platform Support**: Azure Commercial, Azure Government, and hybrid environments
- **Compliance Frameworks**: NIST SP 800-53, FedRAMP, StateRAMP, CJIS support
- **Enterprise Scale**: Multi-region deployments with disaster recovery capabilities
- **Automation**: Comprehensive workflow automation for security operations
- **Government Grade**: Enhanced security features for government and regulated industries
- **DevSecOps Integration**: Security scanning and gates for CI/CD pipelines
- **Threat Hunting**: Automated hunting queries with intelligence feed integration
- **Incident Response**: Complete playbook automation with evidence collection

## Requirements

- PowerShell 5.1 or later
- Azure PowerShell modules (Az.*)
- Appropriate Azure permissions (Security Admin, Contributor)
- Azure subscription with Microsoft Defender for Cloud enabled

## Breaking Changes

This is the initial release, no breaking changes.

## Bug Fixes

This is the initial release, no bug fixes.

## Known Issues

- Government cloud deployments require Azure Government subscription
- Some advanced features require Microsoft Sentinel for full functionality
- Threat intelligence feeds require external API access

## Deprecations

This is the initial release, no deprecations.
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            ExternalModuleDependencies = @(
                'Az.Accounts',
                'Az.Resources',
                'Az.Security',
                'Az.Monitor',
                'Az.OperationalInsights',
                'Az.Automation',
                'Az.LogicApp',
                'Az.KeyVault',
                'Az.Storage',
                'Az.Compute',
                'Az.Network'
            )
        } # End of PSData hashtable
    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI          = 'https://docs.microsoft.com/en-us/azure/defender-for-cloud/'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
